seed: null
env_path: null
group: "husk_random_vision"
record_video: true
device: null

env:
  name: 'husk-random'
  params:
    hud: false
    verbose: false
    port: 8000
    render_action: true

wrappers:
  - name: 'ActionWrapper'
    enabled_actions:
      - NO_OP
      - FORWARD
      - BACKWARD
      - STRAFE_LEFT
      - STRAFE_RIGHT
      - TURN_LEFT
      - TURN_RIGHT

  - name: 'VisionWrapper'
    x_dim: 114
    y_dim: 64
  - name: 'AvoidDamageWrapper'
    damage_reward: -0.1
    alive_reward: 0.5

algorithm:
  name:
    "VisionDQNAlgorithm"
  params:
    num_episodes: 1000
    warmup_episodes: 10
    steps_per_episode: 400
    test_frequency: 10
    solved_criterion:
      name: 'ScoreCriterion'
      params:
        min_episode: 500
        min_avg_score: 195
        min_test_score: 195
        min_avg_test_score: 195
    hidden_dim: 128
    kernel_size: 5
    stride: 2
    device: null
    epsilon_init: 1.0
    epsilon_decay: 0.99
    epsilon_min: 0.01
    update_frequency: 1000
    train_frequency: 1
    replay_buffer_size: 1000000
    batch_size: 256
    gamma: 0.99
    learning_rate: 0.00001
    weight_decay: 0.00001
    tau: 1.0


