# https://github.com/pybind/scikit_build_example/blob/master/.github/workflows/wheels.yml
name: Wheels-cuda

on: [workflow_call]

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cuda-linux
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Wheels on nvidia/cuda:12.6.3-devel-ubuntu22.04
    runs-on: ubuntu-latest
    container:
        image: nvidia/cuda:12.6.3-devel-ubuntu22.04
    strategy:
      fail-fast: false
    steps:
    - name: Install Git 2.18 or higher
      run: |
        apt-get update
        apt-get install -y git cmake ninja-build
        git --version

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        update-environment: false
        check-latest: false
        allow-prereleases: false
    - name: Install cmake
      run: |
        python3 -m pip install cmake
        cmake --version

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: astral-sh/setup-uv@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_SKIP: cp36-* cp37-* cp38-*
        CIBW_ENABLE: cpython-prerelease
        CIBW_ARCHS_LINUX: "x86_64"

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.image }}
        path: wheelhouse/*.whl